#**author :Bitingo Josaphat JB**

In [40]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding
import matplotlib.pyplot as plt

In [41]:
reviews = [
           'nice food',
           'amazing restaurant',
           'too good',
           'just loved it!',
           'will go again',
           'horrible food',
           'never go there',
           'poor service',
           'poor quality',
           'needs improvement'
]

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [42]:
one_hot('amazing food',30) #the second parameter is just the vocab_size

[25, 19]

In [43]:
vocab_size = 50
encoded_reviews = [one_hot(d,vocab_size) for d in reviews]
print(encoded_reviews)

[[43, 35], [13, 24], [23, 12], [20, 8, 24], [26, 21, 2], [9, 35], [34, 21, 9], [22, 12], [22, 43], [40, 19]]


In [52]:
encoded_reviews

[[43, 35],
 [13, 24],
 [23, 12],
 [20, 8, 24],
 [26, 21, 2],
 [9, 35],
 [34, 21, 9],
 [22, 12],
 [22, 43],
 [40, 19]]

In [44]:
# fig , ax1 = plt.subplots(figsize=(8,5))
# for i in encoded_reviews:
#   # print(i)
#   ax1.plot(i,color='red');

#padding my data

In [45]:
max_lengh = 3
padded_reviews = pad_sequences(encoded_reviews,maxlen=max_lengh,padding='post')
print(padded_reviews)

[[43 35  0]
 [13 24  0]
 [23 12  0]
 [20  8 24]
 [26 21  2]
 [ 9 35  0]
 [34 21  9]
 [22 12  0]
 [22 43  0]
 [40 19  0]]


#creating my Model

In [46]:
embedded_vector_size = 4

model = Sequential()
model.add(Embedding(vocab_size,embedded_vector_size,input_length=max_lengh,name = "embedding"))
model.add(Flatten())
model.add(Dense(1,activation='sigmoid'))

In [47]:
X = padded_reviews
y = sentiment

In [48]:
model.compile(optimizer = 'adam',
              loss = 'binary_crossentropy',
              metrics = ['accuracy'])
model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 3, 4)              200       
                                                                 
 flatten_2 (Flatten)         (None, 12)                0         
                                                                 
 dense_2 (Dense)             (None, 1)                 13        
                                                                 
Total params: 213
Trainable params: 213
Non-trainable params: 0
_________________________________________________________________


In [49]:
model.fit(X,y,epochs=50,verbose=0) #"Verbose mode" is an option available in many computer operating systems and programming languages that provides additional details as to what the computer is doing and what drivers and software it is loading during startup or in programming it would produce detailed output for diagnostic purposes

In [50]:
# evaluate my model

loss, accuracy = model.evaluate(X,y)
accuracy

1/1 [==============================] - 0s 109ms/step - loss: 0.6474 - accuracy: 1.0000


1.0

In [51]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

50

In [53]:
encoded_reviews

[[43, 35],
 [13, 24],
 [23, 12],
 [20, 8, 24],
 [26, 21, 2],
 [9, 35],
 [34, 21, 9],
 [22, 12],
 [22, 43],
 [40, 19]]

In [55]:
weights[43]

array([ 0.01809383, -0.06915229,  0.00834266,  0.02992861], dtype=float32)

In [57]:
weights[12]

array([-0.03293073,  0.0273877 , -0.02779353,  0.01160967], dtype=float32)