#This is notebook we are going to learn some fundamentals of tensors using Tensorflow 

In [1]:
# Import Tensorflow


import tensorflow as tf
print(tf.__version__)

2.7.0


In [2]:
# Creating Tensors with tf.constant()

scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
#  Checking the number of dimension of a tensor using ndim

scalar.ndim

0

In [4]:
# creating a Vector

vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
# checking Our Vector dimension

vector.ndim

1

In [6]:
# Creating a Matrix ( a matrix has more than 1 dimension)

matrix = tf.constant([[10,7],
                      [7,100]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 10,   7],
       [  7, 100]], dtype=int32)>

In [7]:
# checking the matrix dimension 

matrix.ndim

2

In [8]:
# creating another matrix with dtype

another_matrix = tf.constant([[10.,7,],
                              [3.,2.],
                              [8.,9.]], dtype = tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [9]:
another_matrix.ndim

2

In [10]:
# let's create a tensor

tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]])

tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [11]:
tensor.ndim

3

what's we've created so far:
* Scalar : single number
* Vector : a number with direction (e.g: wind speed and direction)
* Matrix : a 2-dimensional array of numbers
* Tensor : an N-dimensional array of number

# Creating Tensor with tf.Variable()

In [12]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [13]:
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])

changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [14]:
# Let's try change one of these elememts

changeable_tensor[0] 

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [15]:
# Let's try change one of these elememts

changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [16]:
# Let's try change one of these elememts in our anchangeable_tensor witch can not be changed

# unchangeable_tensor[0].assign(2)
# unchangeable_tensor

#Creating Random Tensor

Random Tensors are Tensors of some abitrary size which contain some random Numbers

In [17]:
# creating two Random (but the same) tensor

random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape = (3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape = (3,2))

# Are they Equal???
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

# Shuffling the Order of Elements in a Tensor

In [18]:
not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [2,5]])
# let's shuffle our non-shuffled tensor

tf.random.shuffle(not_shuffled), not_shuffled.ndim

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 2,  5],
        [ 3,  4]], dtype=int32)>, 2)

In [19]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

# Other Ways to Make Tensors

In [20]:
# Creating a Tensor of all Ones
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [21]:
# Creating a Tensor Of All zeros

tf.zeros([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

# You can also turn Numpy array into Tensors

* The difference between Numpy array and Tensorflow Tensors is that Tensor can be run of GPU much Faster. But Otherwise They're the same

In [22]:
#You can also turn Numpy array into Tensors
import numpy as np
numpy_A = np.arange(1,25, dtype = np.int32) #create a numpy array of values between 1 and 25 with int32 as data type
numpy_A
# X = tf.constant(some_matrix) # This is caital for a Matrix or Tensor
# Y = tf.constant(vector) # This is not capital for vector 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [23]:
A = tf.constant(numpy_A,  shape = (2,3,4))
B = tf.constant(numpy_A)
A, B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

#Getting Information from Tensors

when dealing with tensors you probably need to be aware of these attributes:
*   Shape
*   Rank
*   Axis or Dimension
*   Size





In [24]:
# Create a Rank 4 Tensor (4 dimension Tensor)
rank_4_tensor = tf.zeros([2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [25]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [26]:
# Get various of Tensor attributes

print('The DataType of every element :',rank_4_tensor.dtype)
print('Number of dimension (Rank):', rank_4_tensor.ndim)
print('Shape of the Tensor :', rank_4_tensor.shape)
print('Element Along the 0 Axis :', rank_4_tensor.shape[0])
print("Element Along the Last Axis :", rank_4_tensor.shape[-1])
print("The Total Number Of all Elements in our Tensor :", tf.size(rank_4_tensor))
print("The Total Number Of all Elements in our Tensor :", tf.size(rank_4_tensor).numpy())

The DataType of every element : <dtype: 'float32'>
Number of dimension (Rank): 4
Shape of the Tensor : (2, 3, 4, 5)
Element Along the 0 Axis : 2
Element Along the Last Axis : 5
The Total Number Of all Elements in our Tensor : tf.Tensor(120, shape=(), dtype=int32)
The Total Number Of all Elements in our Tensor : 120


### Indeing Tensors

Tensors can indexed just like Python List.

In [27]:
some_list = [1,2,3,4]
some_list[:2]

[1, 2]

In [28]:
#  Getting The first 2 elements of each dimension

rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [29]:
#  Get The First element from the each dimension from each index except the last one
some_list[:1]


[1]

In [30]:
rank_4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [31]:
rank_4_tensor[:1, :1, :, :1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [32]:
# Creating a Rank 2 Tensor

rank_2_tensor = tf.constant([[10,7],
                             [3,4]])
rank_2_tensor, rank_2_tensor.shape, rank_2_tensor.ndim

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int32)>, TensorShape([2, 2]), 2)

In [33]:
some_list, some_list[-1]

([1, 2, 3, 4], 4)

In [34]:
# Get the last item of each row of our Tensor
rank_2_tensor[:,-1] , rank_4_tensor[:,-1]

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>,
 <tf.Tensor: shape=(2, 4, 5), dtype=float32, numpy=
 array([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],
 
        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]], dtype=float32)>)

In [35]:
# Let's add a new dimension to our rank-2-tensor without affecting the former data

rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [36]:
# an Alternative to adding a new dimension to our rank-2-tensor without affecting the former data at the last position
# Expand the last axis
tf.expand_dims(rank_2_tensor, axis = -1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [37]:
# Expand the 0 axis
tf.expand_dims(rank_2_tensor,0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

### Tensor manipulation (Tensor Operations)
**Basic Operations**
`+`,`-`,`*`,`/`

In [38]:
# you can Add values to a tensor using addition Operator
tensor = tf.constant([[10,7],
                      [3,4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [39]:
# Original Tensor is unchanged

tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [40]:
# Multiplication also Works

tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [41]:
# Substraction also works

tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [42]:
# We can use some tensorflow built-in functions too

tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

## Matrix multiplication
in Machine learning Matrix multiplication is one of the most uself Operation.
There are 2 rules that our matrices or Tensors need to fulfil if we need to matrix multiply them:
1. The Inner dimensions must match
2. The Resulting Matrix  has the shape of the outer dimensions 

In [43]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [44]:
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [45]:
# matrix multipplication with python using this special character @

tensor @ tensor , tensor * tensor # Very differnt method

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[121,  98],
        [ 42,  37]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[100,  49],
        [  9,  16]], dtype=int32)>)

In [46]:
# Create a tensor with (3,2) ndim

X = tf.constant([[1,2],
                 [3,4],
                 [5,6]])

# Create an other Tensor of (3,2) ndim
Y = tf.constant([[7,8],
                 [9,10],
                 [11,12]])

X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [47]:
# Multiplying Tensor of the same shape
# First let's reshape the Y tensor

tf.reshape(Y, shape = (2,3)) , Y


(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  8,  9],
        [10, 11, 12]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [48]:
X.shape, tf.reshape(Y, shape = (2,3)).shape

(TensorShape([3, 2]), TensorShape([2, 3]))

In [49]:
X @ tf.reshape(Y, shape = (2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [50]:
tf.matmul(X, tf.reshape(Y, shape = (2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [51]:
# Trying to change the shape of the X tensor
tf.matmul(tf.reshape(X, shape = (2,3)),Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [52]:
tf.reshape(X, shape = (2,3)).shape , Y.shape

(TensorShape([2, 3]), TensorShape([3, 2]))

In [53]:
# We can try to do the same with tf.Transpose()
X, tf.transpose(X), tf.reshape(X, shape = (2,3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

**The dot Product**
Matrix multiplication is also referred to as the dot product.
You can perfom matrix multiplication Using:
* `tf.matmul()`
* `tf.tensordot()`
* `@ Operator`

In [54]:
# Let's recall of what are the values of X and Y

In [55]:
# perfoming The dot Product on X and Y (requires X or Y to be transposed)

tf.tensordot(tf.transpose(X),Y,axes = 1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

###Changing The Data type of a Tensor

In [56]:
# Creating a New Tensor with default datatype

B = tf.constant([1.7, 7.4])
B.dtype , B

(tf.float32,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>)

In [57]:
C = tf.constant([7,10])
C.dtype

tf.int32

In [58]:
# Changing from float32 to float16 (Reduced Precision)

D = tf.cast(B, dtype = tf.float16)
D

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

In [59]:
# Changing from int32 to float32 
E = tf.cast(C, dtype = tf.float32)
E

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>

### Aggregating Tensors
aggregating tensors = condensing them from the multiple values to a smaller amount of values.

In [60]:
# let's Create a New Tensor
D = tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [61]:
# Get the absolute value of a certain Tensor
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Let's go through  the following forms of aggregation :
* Get the minimun
* Get the Maximum
* Get The Mean of a tensor
* Get The sum of a tensor

In [62]:
#  let's Create a random Tensor with values between 0 and 100 of size 50

E = tf.constant(np.random.randint(0,100,50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([37,  5, 97, 20, 32, 69, 99, 34, 66, 83, 91, 67, 96, 37, 59, 95, 44,
       29, 92, 46, 49, 28, 60, 28, 31, 56, 47, 12, 50,  2, 45, 55, 11, 23,
       44, 61, 72, 48,  8,  5, 58, 83, 13, 30, 18,  3, 21, 22, 80, 72])>

In [63]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [64]:
# Find the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [65]:
# Find the Maximun
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [66]:
# Find The sum of a Tensor
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2333>

In [67]:
# Find the Variance of a Tensor with Tensorflow-probability
import tensorflow_probability as tfp
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=783>

In [68]:
# Find the Variance of a Tensor with math module
tf.math.reduce_variance(tf.cast(E, dtype= tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=783.4244>

In [69]:
# Find the standard deviation of our Tensor
tf.math.reduce_std(tf.cast(E, dtype = tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=27.98972>

**Find the positional maximum and minimum**

In [70]:
# create a new tensor for finding the positional minimum and maximum

tf.random.set_seed(42)
F = tf.random.uniform(shape = [50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [71]:
# Find The Positional Maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [72]:
#  Index on our lagest value position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [73]:
# Find the max Value of F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [74]:
# assert F[tf.argmax(F)] != tf.reduce_max(F)
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [75]:
# Find the Positional Minimum
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [76]:
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [77]:
# Find the value on our indexed position
tf.reduce_min(F),tf.reduce_min(F) ==F[tf.argmin(F)]

(<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>,
 <tf.Tensor: shape=(), dtype=bool, numpy=True>)

### Squeezing a Tensor (Removing all single Dimensions)

In [78]:
# creating a new Tensor to Get started

tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape= [50]), shape = (1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [79]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [80]:
G_squeezed = tf.squeeze(G)
G_squeezed , G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>, TensorShape([50]))

### One-Hot Encoding Tensors

In [81]:
# Creating a list indices

some_list = [0,1,2,3] # could be red, green , blue,  purple

# One Hot encode our list indices
tf.one_hot(some_list, depth = 4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [82]:
#  Specifying the custom values for one hot encoding

tf.one_hot(some_list, depth=4, on_value = 'JB', off_value = 'AI')

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'JB', b'AI', b'AI', b'AI'],
       [b'AI', b'JB', b'AI', b'AI'],
       [b'AI', b'AI', b'JB', b'AI'],
       [b'AI', b'AI', b'AI', b'JB']], dtype=object)>

### Squaring , Log, Square Root

In [83]:
# Creating a new Tensor

H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [84]:
# Squaring it
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [85]:
tf.sqrt(F) # will error , method requires non-int type values

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.8152067 , 0.6640834 , 0.59403914, 0.6815296 , 0.18346773,
       0.8274493 , 0.86030066, 0.93404734, 0.47573766, 0.47243717,
       0.5571248 , 0.8499034 , 0.36494818, 0.74031335, 0.7580296 ,
       0.9485165 , 0.09728139, 0.72196305, 0.796583  , 0.44646195,
       0.8540623 , 0.7388061 , 0.32797182, 0.8226214 , 0.8125738 ,
       0.5804743 , 0.7755112 , 0.45893982, 0.92343765, 0.66379344,
       0.97392386, 0.48736632, 0.90099555, 0.7254925 , 0.7030704 ,
       0.4648962 , 0.9196301 , 0.93374735, 0.55532527, 0.82873625,
       0.4874838 , 0.88415086, 0.98343194, 0.26210994, 0.8937222 ,
       0.8125805 , 0.76625794, 0.40573013, 0.85912883, 0.5661629 ],
      dtype=float32)>

In [86]:
# Find the Square Root
tf.sqrt(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [88]:
tf.math.log(H) # will error , method requires non-int type values

In [89]:
# Find the Log
tf.math.log(tf.cast(H, dtype = tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensors and Numpy

Tensorflow interacts beautifully with numpy arrays

In [90]:
# Creating a new Tensor
J = tf.constant(np.array([3.,7.,10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [91]:
# Convert Our Tensor Back Into a Numpy array
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [92]:
# Convert a Tensor into a Numpy array
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [93]:
J = tf.constant([3.])
J.numpy, J.numpy()[0]

(<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(1,), dtype=float32, numpy=array([3.], dtype=float32)>>,
 3.0)

In [94]:
# The default types of each are slightly different
numpy_J = tf.constant(np.array([3.,7.,10]))
tensor_J = tf.constant([3.,7.,10])


numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)